### ISSUE TITLE
Rename the branch `master` to `main` to match the TFX Addons pattern

### ISSUE THREAD

**Issue by codesue** [tensorflow/model-card-toolkit#253]
### Discussed in https://github.com/tensorflow/model-card-toolkit/discussions/236

<div type='discussions-op-text'>
<sup>Originally posted by **hanneshapke** October 26, 2022</sup>

Should we rename `master` to `main` to match the TFX Addons pattern?

Why? 
https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main
</div>

---

- [x] Post a discussion topic in the [Announcements category](https://github.com/tensorflow/model-card-toolkit/discussions/categories/announcements) to notify contributors about this change. Be sure to provide context on why the change is happening, the anticipated timeline for when the change will happen, and any action items for contributors. If you don't have the right permissions to do this yourself, tag `@hanneshapke` or `@codesue` so they can publish the post on your behalf.
- [x] Replace relevant [mentions of "master" in the codebase](https://github.com/tensorflow/model-card-toolkit/search?p=1&q=master) with "main" and submit a pull request with your changes.
- [x] If you have permissions to update repo settings, merge your approved pull request and follow the instructions in [GitHub's renaming a branch guide](https://github.com/github/renaming#rename-existing) to rename "master" to "main". If you don't have the right permissions to do this yourself, tag `@hanneshapke` or `@codesue` so they can merge your branch and rename the default branch.

**Comment by sklin93** [comment]
@codesue Hi Sue, I don't seem to have permission to post on the announcement page. Could you please post an announcement? About the post content:
- Why the change is happening: https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main (same link as mentioned by you above)
- Timeline: the code is ready, so it really depends on what is more convenient for contributors (since there's the holiday); what do you recommend? This week or the first week of Jan?
- Action items for contributors: follow the "What Your Teammates Have to Do" section on [this page](https://www.git-tower.com/learn/git/faq/git-rename-master-to-main).

Thank you!

**Comment by sklin93** [comment]
The first weekend of January (Jan 7-8) would be better! Thank you @codesue!

**Comment by sklin93** [comment]
@codesue hi Sue, I created the pull request. Could you review, approve and merge it when you have time? Thanks!
