### ISSUE TITLE
Code on GITHUB is different to the one in pip repository

### ISSUE THREAD

**Issue by m-markovic** [tensorflow/model-card-toolkit#61]
## Expected Behavior
Should be able to run the example with code imported from GITHUB rather than using pip install

## Actual Behavior
compilation error thrown at line 50 in https://github.com/tensorflow/model-card-toolkit/blob/master/model_card_toolkit/utils/tfx_util.py 

## Steps to Reproduce the Problem

1. Import the module locally with the code downloaded from GITHUB (I did it in colab and imported from one drive) 
2. Importing of module will fail due missing attribute in mlmd variable

## Specifications

- Version:
- Platform: colab

**Comment by codesue** [comment]
Hi @m-markovic, thanks for raising this! I realize you reported this issue a while ago, but are you still running into this error?

**Comment by codesue** [comment]
Hi @m-markovic, I'm going to close this issue, but feel free to reopen it if you believe it was closed in error.

There isn't enough information here for me to be certain about what's causing this issue, but I've had similar errors when I've tried to run a notebook without restarting the kernel after running `!pip install ...`. Because of how Colab loads packages, you have to restart the kernel after installing packages for the first time.
